#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

name: Code Coverage Report

on: [push, pull_request]

jobs:
  report test coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Check out your repository
    - run: yarn install # Install dependencies
    - run: yarn test-coverage # Run test
    - run: yarn codecov # Upload to Codecov
